### ISSUE TITLE
Group channels by ROI

### ISSUE THREAD

**Issue by nilseling** [BodenmillerGroup/napari-imc#5]
When opening an .mcd with multiple ROIs, would it be possible to group the channels by ROI? Otherwise there will be e.g. 5x40 channels available to chose from when selecting 5 ROIs.

**Comment by jwindhager** [comment]
Thank you for opening this issue. Yes, I noticed the same. Unfortunately, to my knowledge, napari doesn't know the concept of grouped layers. It's still a relatively young project, so support for this might be added in the future (feel free to open an issue with the napari project). However, for the meantime, I think it would be relatively straight-forward to add separate "Channels" and "ROI" panels, in which only the channels/ROIs are displayed (e.g., 40 items/5 items instead of 5x40). What do you think, @nilseling?

**Comment by nilseling** [comment]
I think that is an excellent idea! Please go ahead and I'm happy to play around with this!

**Comment by jwindhager** [comment]
For reference:
- Discussion on widget plugin hookspec https://github.com/napari/napari/issues/1327
- OMERO Widget https://github.com/tlambert03/napari-omero
